name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for opening up your first issue!🎉 Your efforts are what makes this project great!'
        pull_request-message: 'Thank you for opening up your first pull request!🎉 Your efforts are what makes this project great!'
